spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/investorwithdrawal
    username: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  liquibase:
    enabled: true
    changeLog: classpath:db/changelogs/changelog-master.yaml
logging.level.org.springframework.web: trace
logging.level.org.apache: trace
logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE
server:
  port: "8443"