spring:
  datasource:
    url: jdbc:h2:mem:investorwithdrawal
    username: sa
    password: admin
    driver-class-name: org.h2.Driver
    initialization-mode: always
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
  liquibase:
    enabled: true
    change-log: classpath:db/changelogs/changelog-master.yaml
logging.level.org.springframework.web: trace
logging.level.org.apache: trace
logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE
server:
  port: "8443"